### ISSUE TITLE
url format

### ISSUE THREAD

**Issue by sedufau** [Saga-UGA/spip_webpage_from_hal#1]
Based on the given example, when I use the following query (hal.univ-grenoble-alpes.fr)

```
http://hal.univ-grenoble-alpes.fr/Public/afficheRequetePubli.php?auteur_exp=boris,morel&CB_auteur=oui&CB_titre=oui&CB_article=oui&langue=Francais&tri_exp=annee_publi&tri_exp2=typdoc&tri_exp3=date_publi&ordre_aff=TA&Fen=Aff&css=../css/VisuRubriqueEncadre.css
```

my spip web site displays the correct content.

However, when I paste the following query in a browser, the address is changed (haltools.archives-ouvertes.fr)

```
http://haltools.archives-ouvertes.fr/Public/afficheRequetePubli.php?auteur_exp=boris,morel&CB_auteur=oui&CB_titre=oui&CB_article=oui&langue=Francais&tri_exp=annee_publi&tri_exp2=typdoc&tri_exp3=date_publi&ordre_aff=TA&Fen=Aff&css=../css/VisuRubriqueEncadre.css
```

With this redirection, no content is displayed in spip.

**Comment by BorisMorel** [comment]
Hi,

Due to https://github.com/Saga-UGA/spip_webpage_from_hal/blob/master/webpage_from_hal_fonctions.php#L9

The ip is checked and only the HAL CCSD machine is authorized. But I don't understand why the host `haltools.archives-ouvertes.fr` return an other ip...

``` bash
host haltools.archives-ouvertes.fr
haltools.archives-ouvertes.fr has address 128.93.162.106

host hal.univ-grenoble-alpes.fr
hal.univ-grenoble-alpes.fr is an alias for ccsdwbvip01.in2p3.fr.
ccsdwbvip01.in2p3.fr has address 193.48.96.10
```

Maybe the team need to be patch this code.

Regards,
Boris.

**Comment by sedufau** [comment]
Hi Boris,
thanks, this makes sense.
I used "hal.univ-grenoble-alpes.fr" for my queries - works like a charm!
Cheers,
Stephane

**Comment by BorisMorel** [comment]
Another tips : 
You can add `&noHeader` at the end of your url to cleanify your embeded html.

http://hal.univ-grenoble-alpes.fr/Public/afficheRequetePubli.php?auteur_exp=boris,morel&CB_auteur=oui&CB_titre=oui&CB_article=oui&langue=Francais&tri_exp=annee_publi&tri_exp2=typdoc&tri_exp3=date_publi&ordre_aff=TA&Fen=Aff&noHeader
