### ISSUE TITLE
Please add a License on your code

### ISSUE THREAD

**Issue by Pigeo** [Saga-UGA/spip_webpage_from_hal#3]
Could you please add a LICENSE.txt file on this repository in order to explicit tell users what are the conditions of reusability of this piece of software (is it MIT License ? BSD ? CECILL ? GPL ? anything else ?)

I'm currently distributing a modified version of your plugin under [HAL-developments/SPIP_integration/plugins/spip_webpage_from_hal](https://github.com/UMR7320/HAL-developments/tree/master/SPIP_integration/plugins/spip_webpage_from_hal%20(version%20modifiee)) and I would like to check if I'm not violating your conditions, but if you don't provide any license it's difficult to know....

**Comment by BorisMorel** [comment]
Done. Master branch
